version: '3'
services:
  syslogger:
    build: .
    container_name: syslogger
    network_mode: host
    volumes:
      - ./logs:/logs
    environment:
      - LOG_FILE=/logs/syslog.log
      - LOG_LEVEL=INFO
      - BIND_HOST=0.0.0.0
      - UDP_PORT=514
      - TCP_PORT=514
      - ENABLE_UDP=true
      - ENABLE_TCP=true
      - ENABLE_WEB=true
      - WEB_PORT=8080
      - WEB_LOG_LINES=100
      - DEAUTH_THRESHOLD=3
      - AUTH_FAIL_THRESHOLD=5
      - PORT_SCAN_THRESHOLD=10
      - DHCP_REQ_THRESHOLD=20
      - FIREWALL_THRESHOLD=20
      - DOS_THRESHOLD=10
      - DB_FILE=/logs/syslog.db
      - DETECTION_WINDOW=600
