version: '3'
services:
  syslogger:
    build: .
    container_name: syslogger
    volumes:
      - ./logs:/logs
    ports:
      - "514:514/udp"
      - "514:514/tcp"
      - "8080:8080"
    environment:
      LOG_FILE: /logs/syslog.log
      LOG_LEVEL: INFO
      BIND_HOST: 0.0.0.0
      UDP_PORT: 514
      TCP_PORT: 514
      ENABLE_UDP: 'true'
      ENABLE_TCP: 'true'
      ENABLE_WEB: 'true'
      WEB_PORT: 8080
      WEB_LOG_LINES: 100
